src/main/java/com/example/capstone_project/controller/responses/user/DepartmentResponse.java

[bug] fix bug

---

src/main/java/com/example/capstone_project/controller/UserController.java
src/main/java/com/example/capstone_project/controller/responses/userManagement/DepartmentResponse.java
src/main/java/com/example/capstone_project/controller/responses/userManagement/PositionResponse.java
src/main/java/com/example/capstone_project/controller/responses/userManagement/RoleResponse.java
src/main/java/com/example/capstone_project/controller/responses/userManagement/UserResponse.java
src/main/java/com/example/capstone_project/utils/mapper/userManagement/UserMapper.java

[feature] change package name

---

src/main/java/com/example/capstone_project/controller/FinancialPlanController.java
src/main/java/com/example/capstone_project/controller/responses/planManagement/DepartmentResponse.java
src/main/java/com/example/capstone_project/controller/responses/planManagement/PlanResponse.java
src/main/java/com/example/capstone_project/controller/responses/planManagement/StatusResponse.java
src/main/java/com/example/capstone_project/controller/responses/planManagement/TermResponse.java

[mock] change package name

---

src/main/java/com/example/capstone_project/controller/DepartmentController.java
src/main/java/com/example/capstone_project/controller/responses/department/paginate/DepartmentPaginate.java
src/main/java/com/example/capstone_project/controller/responses/department/paginate/DepartmentPaginateResponse.java

[mock] plan paging department *

---

src/main/java/com/example/capstone_project/controller/FinancialPlanController.java
src/main/java/com/example/capstone_project/controller/responses/Responses.java
src/main/java/com/example/capstone_project/controller/responses/plan/StatusResponse.java
src/main/java/com/example/capstone_project/controller/responses/plan/list/PlanResponse.java

[mock] plan paging status *

---

src/main/java/com/example/capstone_project/controller/UserController.java
src/main/java/com/example/capstone_project/controller/body/user/update/UpdateUserBody.java
src/main/java/com/example/capstone_project/utils/mapper/user/edit/UpdateUserToUserDetailResponseMapper.java

[mock] Update user, add validation

---

src/main/java/com/example/capstone_project/controller/ReportController.java
src/main/java/com/example/capstone_project/controller/body/report/delete/DeleteReportBody.java

[mock] report delete mock api

---

src/main/java/com/example/capstone_project/config/GlobalExceptionHandler.java
src/main/java/com/example/capstone_project/controller/TermController.java
src/main/java/com/example/capstone_project/controller/UserController.java
src/main/java/com/example/capstone_project/controller/body/term/create/CreateTermBody.java
src/main/java/com/example/capstone_project/controller/body/term/delete/DeleteTermBody.java
src/main/java/com/example/capstone_project/controller/body/term/update/UpdateTermBody.java
src/main/java/com/example/capstone_project/controller/body/user/delete/DeleteUserBody.java
src/main/java/com/example/capstone_project/controller/body/user/update/UpdateUserBody.java
src/main/java/com/example/capstone_project/entity/Term.java
src/main/java/com/example/capstone_project/entity/TermDuration.java
src/main/java/com/example/capstone_project/utils/mapper/term/update/UpdateTermBodyToTermDetailResponseMapper.java

[mock] delete user , add validation, check number for ID

---

src/main/java/com/example/capstone_project/controller/UserController.java
src/main/java/com/example/capstone_project/controller/body/user/activate/ActivateUserBody.java
src/main/resources/application.properties

[mock] add mock activate user api

---

src/main/java/com/example/capstone_project/controller/AnnualReportController.java
src/main/java/com/example/capstone_project/controller/responses/annualReport/expenses/AnnualReportExpenseResponse.java
src/main/java/com/example/capstone_project/controller/responses/annualReport/expenses/CostTypeResponse.java
src/main/resources/application.properties

[mock] add annual report-expenses

---

src/main/java/com/example/capstone_project/controller/AnnualReportController.java
src/main/java/com/example/capstone_project/controller/ReportController.java
src/main/java/com/example/capstone_project/controller/responses/annualReport/list/AnnualReportResponse.java

[mock] add mock api annual report list

---

src/main/java/com/example/capstone_project/config/GlobalCorsConfiguration.java
src/main/java/com/example/capstone_project/config/SecurityConfiguration.java
src/main/resources/application.properties

[feature] fix global cors

---

src/main/java/com/example/capstone_project/controller/AnnualReportController.java
src/main/java/com/example/capstone_project/controller/ReportController.java
src/main/java/com/example/capstone_project/controller/RoleController.java
src/main/java/com/example/capstone_project/service/RoleService.java
src/main/java/com/example/capstone_project/service/impl/RoleServiceImpl.java
src/main/java/com/example/capstone_project/utils/mapper/user/role/RoleToRoleResponseMapper.java

[feature] down menu role list user management/user create/user edit

---

src/main/java/com/example/capstone_project/controller/FinancialPlanController.java
src/main/java/com/example/capstone_project/service/FinancialPlanService.java
src/main/java/com/example/capstone_project/service/impl/FinancialPlanServiceImpl.java

[feature] plan delete

---

src/main/java/com/example/capstone_project/controller/UserController.java
src/main/java/com/example/capstone_project/service/UserService.java
src/main/java/com/example/capstone_project/service/impl/UserServiceImpl.java
src/main/resources/application.properties

[feature] add active user

---

src/main/java/com/example/capstone_project/controller/UserController.java
src/main/java/com/example/capstone_project/controller/body/user/changePassword/ChangePasswordBody.java
src/main/java/com/example/capstone_project/service/UserService.java
src/main/java/com/example/capstone_project/service/impl/UserServiceImpl.java
src/main/resources/application.properties

[mock] add change password

---

src/main/java/com/example/capstone_project/config/SecurityConfiguration.java
src/main/java/com/example/capstone_project/controller/UserController.java
src/main/java/com/example/capstone_project/controller/body/user/forgotPassword/ForgetPasswordEmailBody.java
src/main/java/com/example/capstone_project/utils/helper/JwtHelper.java
src/main/resources/application.properties

[mock] add forgot password email

---

src/main/java/com/example/capstone_project/config/SecurityConfiguration.java
src/main/java/com/example/capstone_project/controller/UserController.java
src/main/java/com/example/capstone_project/controller/body/user/otp/OTPBody.java
src/main/java/com/example/capstone_project/service/UserService.java
src/main/java/com/example/capstone_project/service/impl/UserServiceImpl.java
src/main/java/com/example/capstone_project/utils/helper/JwtHelper.java
src/main/resources/application.properties

[mock] add otp validate

---

src/main/java/com/example/capstone_project/config/SecurityConfiguration.java
src/main/java/com/example/capstone_project/controller/UserController.java
src/main/java/com/example/capstone_project/controller/body/user/resetPassword/ResetPasswordBody.java
src/main/java/com/example/capstone_project/service/UserService.java
src/main/java/com/example/capstone_project/service/impl/UserServiceImpl.java

[mock] add reset password

---

src/main/java/com/example/capstone_project/utils/helper/UserHelper.java
src/test/java/term/TermServiceTest.java

[test] Service create term

---

src/main/java/com/example/capstone_project/config/SeedConfiguration.java
src/main/java/com/example/capstone_project/controller/FinancialPlanController.java
src/main/java/com/example/capstone_project/controller/body/expense/ApprovalExpenseBody.java
src/main/java/com/example/capstone_project/entity/ExpenseStatus.java
src/main/java/com/example/capstone_project/repository/FinancialPlanExpenseRepository.java
src/main/java/com/example/capstone_project/repository/FinancialPlanFileRepository.java
src/main/java/com/example/capstone_project/repository/TermRepository.java
src/main/java/com/example/capstone_project/service/FinancialPlanService.java
src/main/java/com/example/capstone_project/service/impl/FinancialPlanServiceImpl.java
src/main/java/com/example/capstone_project/utils/exception/InvalidInputException.java

[feature] expense approval

---

src/main/java/com/example/capstone_project/controller/TermController.java
src/main/java/com/example/capstone_project/controller/body/term/update/UpdateTermBody.java
src/main/java/com/example/capstone_project/entity/Term.java
src/main/java/com/example/capstone_project/service/TermService.java
src/main/java/com/example/capstone_project/service/impl/TermServiceImpl.java
src/main/java/com/example/capstone_project/utils/exception/term/InvalidDateException.java
src/main/java/com/example/capstone_project/utils/mapper/term/update/UpdateTermBodyToTermDetailResponseMapper.java
src/test/java/term/TermServiceTest.java

[feature] update term

---

src/main/java/com/example/capstone_project/controller/TermController.java
src/main/java/com/example/capstone_project/controller/UserController.java
src/main/java/com/example/capstone_project/service/TermService.java
src/main/java/com/example/capstone_project/service/impl/TermServiceImpl.java

[feature] start term manually

---

src/main/java/com/example/capstone_project/controller/ReportController.java
src/main/java/com/example/capstone_project/controller/responses/report/detail/ReportDetailResponse.java
src/main/java/com/example/capstone_project/repository/FinancialReportRepository.java
src/main/java/com/example/capstone_project/repository/result/ReportDetailResult.java
src/main/java/com/example/capstone_project/service/FinancialReportService.java
src/main/java/com/example/capstone_project/service/impl/FinancialReportServiceImpl.java
src/main/java/com/example/capstone_project/utils/mapper/report/detail/ReportDetailMapper.java

[feature] report detail v2

---

src/main/java/com/example/capstone_project/controller/ReportController.java
src/main/java/com/example/capstone_project/controller/responses/report/calculate/ReportActualCostResponse.java
src/main/java/com/example/capstone_project/controller/responses/report/calculate/ReportExpectedCostResponse.java
src/main/java/com/example/capstone_project/repository/FinancialReportRepository.java
src/main/java/com/example/capstone_project/service/FinancialReportService.java
src/main/java/com/example/capstone_project/service/impl/FinancialReportServiceImpl.java

[feature] calculate actual cost and expected cost

---

src/main/java/com/example/capstone_project/controller/CostTypeController.java
src/main/java/com/example/capstone_project/service/CostTypeService.java
src/main/java/com/example/capstone_project/service/impl/CostTypeServiceImpl.java

[feature] add get all list cost type

---

src/main/java/com/example/capstone_project/controller/DepartmentController.java
src/main/java/com/example/capstone_project/service/DepartmentService.java
src/main/java/com/example/capstone_project/service/impl/DepartmentServiceImpl.java

[feature] add get all department

---

src/main/java/com/example/capstone_project/controller/UserController.java

Thay đổi message trong response body thành object dưới dạng Json hoặc để null 

---

src/main/java/com/example/capstone_project/config/SeedConfiguration.java
src/main/java/com/example/capstone_project/controller/FinancialPlanController.java
src/main/java/com/example/capstone_project/controller/ReportController.java
src/main/java/com/example/capstone_project/controller/body/expense/ApprovalAllExpenseBody.java
src/main/java/com/example/capstone_project/controller/body/expense/ApprovalExpenseBody.java
src/main/java/com/example/capstone_project/controller/body/expense/DenyExpenseBody.java
src/main/java/com/example/capstone_project/repository/FinancialPlanExpenseRepository.java
src/main/java/com/example/capstone_project/repository/FinancialReportRepository.java
src/main/java/com/example/capstone_project/repository/impl/FinancialPlanExpenseRepositoryImpl.java
src/main/java/com/example/capstone_project/repository/result/ReportExpenseResult.java
src/main/java/com/example/capstone_project/service/FinancialPlanService.java
src/main/java/com/example/capstone_project/service/FinancialReportService.java
src/main/java/com/example/capstone_project/service/impl/FinancialPlanServiceImpl.java
src/main/java/com/example/capstone_project/service/impl/FinancialReportServiceImpl.java
src/main/java/com/example/capstone_project/utils/enums/ReportStatusCode.java
src/main/java/com/example/capstone_project/utils/helper/RemoveDuplicateHelper.java
src/main/java/com/example/capstone_project/utils/mapper/report/expenses/ReportExpenseResponseMapper.java

[feature] change approval feature plan to report and update sql query for list expense report, calculate actual cost and calculate expected cost feature, and add binding Result to handle exception

[feature] report approval expenses

---

src/main/java/com/example/capstone_project/repository/FinancialPlanRepository.java
src/main/java/com/example/capstone_project/service/impl/FinancialPlanServiceImpl.java

[feature] plan version fix bug

---

src/main/java/com/example/capstone_project/controller/ReportController.java
src/main/java/com/example/capstone_project/controller/body/expense/ExpenseBody.java
src/main/java/com/example/capstone_project/controller/body/expense/UploadReportExpenses.java
src/main/java/com/example/capstone_project/repository/FinancialPlanExpenseRepository.java
src/main/java/com/example/capstone_project/service/FinancialReportService.java
src/main/java/com/example/capstone_project/service/impl/FinancialReportServiceImpl.java
src/main/java/com/example/capstone_project/utils/helper/RemoveDuplicateHelper.java

[feature] report upload

---

src/main/java/com/example/capstone_project/controller/TermController.java
src/main/java/com/example/capstone_project/repository/impl/TermRepositoryImpl.java
src/main/java/com/example/capstone_project/service/impl/UserServiceImpl.java

[update] suửa response body của term, fix bug filter status

---

src/main/java/com/example/capstone_project/config/GlobalExceptionHandler.java
src/main/java/com/example/capstone_project/controller/UserController.java
src/main/java/com/example/capstone_project/controller/body/user/create/CreateUserBody.java
src/main/java/com/example/capstone_project/controller/body/user/update/UpdateUserBody.java
src/main/java/com/example/capstone_project/entity/User.java
src/main/java/com/example/capstone_project/service/impl/UserServiceImpl.java
src/test/java/exceptionHandlerTest/ExceptionHandlerTest.java

[update] fix validation for reset password, update regex for full name,  add more handling code , add validation to update user

---

src/main/java/com/example/capstone_project/controller/ReportController.java
src/main/java/com/example/capstone_project/controller/body/expense/ExpenseBody.java
src/main/java/com/example/capstone_project/controller/body/expense/UploadReportExpenses.java
src/main/java/com/example/capstone_project/repository/FinancialPlanExpenseRepository.java
src/main/java/com/example/capstone_project/service/FinancialReportService.java
src/main/java/com/example/capstone_project/service/impl/FinancialReportServiceImpl.java
src/main/java/com/example/capstone_project/utils/helper/RemoveDuplicateHelper.java
src/main/java/com/example/capstone_project/utils/mapper/annual/AnnualReportPaginateResponseMapper.java

[bug] annual report list fix bug mapping

---

src/main/java/com/example/capstone_project/controller/FinancialPlanController.java
src/main/java/com/example/capstone_project/repository/CustomFinancialPlanExpenseRepository.java
src/main/java/com/example/capstone_project/repository/FinancialPlanExpenseRepository.java
src/main/java/com/example/capstone_project/repository/impl/FinancialPlanExpenseRepositoryImpl.java
src/main/java/com/example/capstone_project/service/FinancialPlanService.java
src/main/java/com/example/capstone_project/service/impl/FinancialPlanServiceImpl.java
src/main/java/com/example/capstone_project/utils/mapper/plan/expenses/PlanExpenseResponseMapper.java

[feature] add filter by projectId, supplierId, picId for plan expenses

---

src/main/java/com/example/capstone_project/controller/ReportController.java
src/main/java/com/example/capstone_project/controller/responses/report/PicResponse.java
src/main/java/com/example/capstone_project/controller/responses/report/ProjectResponse.java
src/main/java/com/example/capstone_project/controller/responses/report/SupplierResponse.java
src/main/java/com/example/capstone_project/controller/responses/report/expenses/ExpenseResponse.java
src/main/java/com/example/capstone_project/repository/CustomFinancialPlanExpenseRepository.java
src/main/java/com/example/capstone_project/repository/FinancialPlanExpenseRepository.java
src/main/java/com/example/capstone_project/repository/impl/FinancialPlanExpenseRepositoryImpl.java
src/main/java/com/example/capstone_project/service/FinancialReportService.java
src/main/java/com/example/capstone_project/service/impl/FinancialReportServiceImpl.java
src/main/java/com/example/capstone_project/utils/mapper/report/expenses/ReportExpenseResponseMapper.java

[feature] add filter by projectId, supplierId, picId for report expenses

---

src/main/java/com/example/capstone_project/controller/responses/report/expenses/ExpenseResponse.java
src/main/java/com/example/capstone_project/repository/impl/FinancialPlanExpenseRepositoryImpl.java
src/main/java/com/example/capstone_project/repository/result/ReportExpenseResult.java
src/main/java/com/example/capstone_project/utils/mapper/report/expenses/ReportExpenseResponseMapper.java

[feature] add expense code to response

---

src/main/java/com/example/capstone_project/controller/responses/expense/list/ExpenseResponse.java
src/main/java/com/example/capstone_project/utils/mapper/plan/expenses/PlanExpenseResponseMapper.java

[feature] add expense code to plan expense

---

src/main/java/com/example/capstone_project/config/SeedConfiguration.java
src/main/java/com/example/capstone_project/controller/ReportController.java
src/main/java/com/example/capstone_project/controller/body/expense/ExpenseBody.java
src/main/java/com/example/capstone_project/repository/FinancialPlanExpenseRepository.java
src/main/java/com/example/capstone_project/repository/FinancialReportRepository.java
src/main/java/com/example/capstone_project/service/impl/FinancialReportServiceImpl.java
src/main/java/com/example/capstone_project/utils/helper/RemoveDuplicateHelper.java

[feature] report approval v2

---

src/main/java/com/example/capstone_project/config/SeedConfiguration.java
src/main/java/com/example/capstone_project/controller/FinancialPlanController.java
src/main/java/com/example/capstone_project/controller/ReportController.java
src/main/java/com/example/capstone_project/controller/responses/expense/CurrencyResponse.java
src/main/java/com/example/capstone_project/controller/responses/expense/list/ExpenseResponse.java
src/main/java/com/example/capstone_project/controller/responses/report/expenses/ExpenseResponse.java
src/main/java/com/example/capstone_project/entity/Currency.java
src/main/java/com/example/capstone_project/entity/FinancialPlanExpense.java
src/main/java/com/example/capstone_project/repository/CurrencyRepository.java
src/main/java/com/example/capstone_project/repository/impl/FinancialPlanExpenseRepositoryImpl.java
src/main/java/com/example/capstone_project/repository/result/ExchangeRateResult.java
src/main/java/com/example/capstone_project/repository/result/ReportExpenseResult.java
src/main/java/com/example/capstone_project/service/FinancialPlanService.java
src/main/java/com/example/capstone_project/service/FinancialReportService.java
src/main/java/com/example/capstone_project/service/impl/FinancialPlanServiceImpl.java
src/main/java/com/example/capstone_project/service/impl/FinancialReportServiceImpl.java
src/main/java/com/example/capstone_project/utils/mapper/plan/expenses/PlanExpenseResponseMapper.java
src/main/java/com/example/capstone_project/utils/mapper/report/expenses/ReportExpenseResponseMapper.java

[feature] exchange money for plan expense and report expense

---

src/main/java/com/example/capstone_project/controller/FinancialPlanController.java
src/main/java/com/example/capstone_project/controller/body/plan/create/ExpenseBody.java
src/main/java/com/example/capstone_project/controller/body/plan/reupload/ReUploadExpenseBody.java
src/main/java/com/example/capstone_project/controller/responses/plan/UserResponse.java
src/main/java/com/example/capstone_project/repository/UserRepository.java
src/main/java/com/example/capstone_project/service/FinancialPlanService.java
src/main/java/com/example/capstone_project/service/impl/FinancialPlanServiceImpl.java
src/main/java/com/example/capstone_project/utils/mapper/plan/create/CreatePlanMapper.java
src/main/java/com/example/capstone_project/utils/mapper/plan/reupload/ReUploadExpensesMapper.java

[feature] upload and reupload plan

---

src/main/java/com/example/capstone_project/controller/UserController.java
src/main/java/com/example/capstone_project/controller/responses/user/diagram/UserDepartmentResponse.java
src/main/java/com/example/capstone_project/controller/responses/user/diagram/UserOverTimeDiagramResponse.java
src/main/java/com/example/capstone_project/repository/UserRepository.java
src/main/java/com/example/capstone_project/repository/result/UserDepartmentDiagramResult.java
src/main/java/com/example/capstone_project/repository/result/UserOverTimeDiagramResult.java
src/main/java/com/example/capstone_project/service/UserService.java
src/main/java/com/example/capstone_project/service/impl/UserServiceImpl.java

[feature] create admin home page diagram

---

src/main/java/com/example/capstone_project/config/SeedConfiguration.java

Tôi đổi cái này chắc không sao đâu phải không? :eyes::eyes::eyes:

[feature] Change department of username5 from communicationDepartment to hrDepartment to receive notification
